export type ShenShaCatalogItem = {
  key: string;
  name: string;
  tone: "吉" | "中" | "凶";
  volume: "common" | "uncommon";
  fullNote: string;
  shortNote: string;
};

export const SHENSHA_CATALOG: ShenShaCatalogItem[] = [
  { key: "common-001", name: "天乙贵人", tone: "吉", volume: "common", fullNote: "贵人救应?主逢凶化缓、易得助力与关键节点的扶持。", shortNote: "主逢凶化缓、易得助力与关键节点的扶持。" },
  { key: "common-002", name: "太极贵人", tone: "吉", volume: "common", fullNote: "悟性灵性?主悟性、理解力、玄学哲思与研究气质。", shortNote: "主悟性、理解力、玄学哲思与研究气质。" },
  { key: "common-003", name: "天德贵人", tone: "吉", volume: "common", fullNote: "德性护持?主有德可依，遇事较易减损化缓。", shortNote: "主有德可依，遇事较易减损化缓。" },
  { key: "common-004", name: "月德贵人", tone: "吉", volume: "common", fullNote: "月令和合?主温和转圜、人情缓冲与协商空间。", shortNote: "主温和转圜、人情缓冲与协商空间。" },
  { key: "common-005", name: "天德合", tone: "吉", volume: "common", fullNote: "德合化缓?主以柔化刚，利修复、和解与缓冲。", shortNote: "主以柔化刚，利修复、和解与缓冲。" },
  { key: "common-006", name: "月德合", tone: "吉", volume: "common", fullNote: "月德合和?主关系润滑、协商与修补。", shortNote: "主关系润滑、协商与修补。" },
  { key: "common-007", name: "三奇贵人", tone: "吉", volume: "common", fullNote: "奇气才华?主才智出众、思路特别、易有非常之机。", shortNote: "主才智出众、思路特别、易有非常之机。" },
  { key: "common-008", name: "文昌贵人", tone: "吉", volume: "common", fullNote: "文书学业?主读写表达、考试、策划与逻辑能力。", shortNote: "主读写表达、考试、策划与逻辑能力。" },
  { key: "common-009", name: "国印贵人", tone: "吉", volume: "common", fullNote: "权印规范?主资质、文凭、证照、体制与头衔加持。", shortNote: "主资质、文凭、证照、体制与头衔加持。" },
  { key: "common-010", name: "福星贵人", tone: "吉", volume: "common", fullNote: "福泽转圜?主福气、缓冲与顺势得利。", shortNote: "主福气、缓冲与顺势得利。" },
  { key: "common-011", name: "德秀贵人", tone: "吉", volume: "common", fullNote: "才德兼备?主修养、审美、表达与名望潜力。", shortNote: "主修养、审美、表达与名望潜力。" },
  { key: "common-012", name: "天厨贵人", tone: "吉", volume: "common", fullNote: "衣食口福?主生活品质、口福、审美与待客之道。", shortNote: "主生活品质、口福、审美与待客之道。" },
  { key: "common-013", name: "金舆", tone: "吉", volume: "common", fullNote: "体面承接?主待遇、体面、资源承接与婚配助益。", shortNote: "主待遇、体面、资源承接与婚配助益。" },
  { key: "common-014", name: "华盖", tone: "中", volume: "common", fullNote: "孤高才艺?主独处、才艺、宗教玄学与审美感。", shortNote: "主独处、才艺、宗教玄学与审美感。" },
  { key: "common-015", name: "将星", tone: "吉", volume: "common", fullNote: "主导掌控?主带头、主事、掌控与执行魄力。", shortNote: "主带头、主事、掌控与执行魄力。" },
  { key: "common-016", name: "学堂", tone: "吉", volume: "common", fullNote: "学习积累?主学习训练、系统吸收与知识沉淀。", shortNote: "主学习训练、系统吸收与知识沉淀。" },
  { key: "common-017", name: "词馆", tone: "吉", volume: "common", fullNote: "表达包装?主文案、包装、策划、说服与传播。", shortNote: "主文案、包装、策划、说服与传播。" },
  { key: "common-018", name: "驿马", tone: "中", volume: "common", fullNote: "迁动奔波?主出行、变动、迁移、跨界与切换。", shortNote: "主出行、变动、迁移、跨界与切换。" },
  { key: "common-019", name: "桃花", tone: "中", volume: "common", fullNote: "人缘魅力?主人缘、感情吸引、社交曝光。", shortNote: "主人缘、感情吸引、社交曝光。" },
  { key: "common-020", name: "红鸾", tone: "吉", volume: "common", fullNote: "喜庆姻缘?主感情升温、婚恋缘分与喜庆联结。", shortNote: "主感情升温、婚恋缘分与喜庆联结。" },
  { key: "common-021", name: "天喜", tone: "吉", volume: "common", fullNote: "喜气临门?主关系转暖、喜事推进与情绪振奋。", shortNote: "主关系转暖、喜事推进与情绪振奋。" },
  { key: "common-022", name: "咸池", tone: "中", volume: "common", fullNote: "情感欲念?主魅力与情欲，也主关系边界问题。", shortNote: "主魅力与情欲，也主关系边界问题。" },
  { key: "common-023", name: "禄神", tone: "吉", volume: "common", fullNote: "资源俸禄?主俸禄、收入、稳定资源与自我驱动力。", shortNote: "主俸禄、收入、稳定资源与自我驱动力。" },
  { key: "common-024", name: "羊刃", tone: "凶", volume: "common", fullNote: "刚烈冲劲?主强势、冲动、对抗、决断与易伤。", shortNote: "主强势、冲动、对抗、决断与易伤。" },
  { key: "common-025", name: "飞刃", tone: "凶", volume: "common", fullNote: "突发锋芒?主急躁、冲撞、突发性伤害与硬碰硬。", shortNote: "主急躁、冲撞、突发性伤害与硬碰硬。" },
  { key: "common-026", name: "天医", tone: "吉", volume: "common", fullNote: "疗愈修复?主养护、医药、修复与照顾能力。", shortNote: "主养护、医药、修复与照顾能力。" },
  { key: "common-027", name: "天赦", tone: "吉", volume: "common", fullNote: "宽赦转机?主事态缓解、得赦、改过与转圜。", shortNote: "主事态缓解、得赦、改过与转圜。" },
  { key: "common-028", name: "天罗", tone: "凶", volume: "common", fullNote: "束缚拖缠?主被关系、规则、杂事牵扯与困住。", shortNote: "主被关系、规则、杂事牵扯与困住。" },
  { key: "common-029", name: "地网", tone: "凶", volume: "common", fullNote: "现实羁绊?主拖延、缠绕、责任纠葛与沉陷。", shortNote: "主拖延、缠绕、责任纠葛与沉陷。" },
  { key: "common-030", name: "孤辰", tone: "中", volume: "common", fullNote: "独担独行?主独立、清冷、凡事爱自己扛。", shortNote: "主独立、清冷、凡事爱自己扛。" },
  { key: "common-031", name: "寡宿", tone: "中", volume: "common", fullNote: "慢热疏离?主关系慢热、孤单感与内向防备。", shortNote: "主关系慢热、孤单感与内向防备。" },
  { key: "common-032", name: "丧门", tone: "凶", volume: "common", fullNote: "忧思挂心?主低压、挂碍、家庭负担与情绪阴影。", shortNote: "主低压、挂碍、家庭负担与情绪阴影。" },
  { key: "common-033", name: "吊客", tone: "凶", volume: "common", fullNote: "外事牵神?主被外界事件、消息、人情牵动心神。", shortNote: "主被外界事件、消息、人情牵动心神。" },
  { key: "common-034", name: "披麻", tone: "凶", volume: "common", fullNote: "劳心劳力?主烦心奔波、家务牵扯、情绪阴耗。", shortNote: "主烦心奔波、家务牵扯、情绪阴耗。" },
  { key: "common-035", name: "劫煞", tone: "凶", volume: "common", fullNote: "干扰掣肘?主计划被打断、资源分流、竞争争夺。", shortNote: "主计划被打断、资源分流、竞争争夺。" },
  { key: "common-036", name: "灾煞", tone: "凶", volume: "common", fullNote: "波折耗损?主波折、失误、消耗与不顺。", shortNote: "主波折、失误、消耗与不顺。" },
  { key: "common-037", name: "亡神", tone: "凶", volume: "common", fullNote: "暗耗失守?主精神消耗、判断失真、暗处阻力。", shortNote: "主精神消耗、判断失真、暗处阻力。" },
  { key: "common-038", name: "勾绞煞", tone: "凶", volume: "common", fullNote: "纠缠是非?主口舌、人情纠缠、误会与拉扯。", shortNote: "主口舌、人情纠缠、误会与拉扯。" },
  { key: "common-039", name: "红艳", tone: "中", volume: "common", fullNote: "艳色外放?主个人魅力强，也易招惹复杂情感。", shortNote: "主个人魅力强，也易招惹复杂情感。" },
  { key: "common-040", name: "流霞", tone: "凶", volume: "common", fullNote: "酒色情绪?主应酬、冲动、情色与情绪化牵连。", shortNote: "主应酬、冲动、情色与情绪化牵连。" },
  { key: "common-041", name: "魁罡", tone: "中", volume: "common", fullNote: "刚毅果断?主标准高、执行强、个性锋利。", shortNote: "主标准高、执行强、个性锋利。" },
  { key: "common-042", name: "金神", tone: "中", volume: "common", fullNote: "刚烈特质?主锋锐、极端、执行猛，也要防过刚。", shortNote: "主锋锐、极端、执行猛，也要防过刚。" },
  { key: "common-043", name: "十灵日", tone: "吉", volume: "common", fullNote: "灵感直觉?主感知力强、灵性足、艺术玄学天分。", shortNote: "主感知力强、灵性足、艺术玄学天分。" },
  { key: "common-044", name: "孤鸾", tone: "中", volume: "common", fullNote: "情路自我?主情感标准高、节奏感强、关系需经营。", shortNote: "主情感标准高、节奏感强、关系需经营。" },
  { key: "common-045", name: "阴差阳错", tone: "凶", volume: "common", fullNote: "时机错位?主沟通错位、缘分错拍、关系误差。", shortNote: "主沟通错位、缘分错拍、关系误差。" },
  { key: "common-046", name: "童子煞", tone: "中", volume: "common", fullNote: "清气孤感?主精神敏感、理想色彩重、俗缘偏薄。", shortNote: "主精神敏感、理想色彩重、俗缘偏薄。" },
  { key: "common-047", name: "元辰", tone: "凶", volume: "common", fullNote: "情绪郁滞?主内耗、郁结、拖延、心神反复。", shortNote: "主内耗、郁结、拖延、心神反复。" },
  { key: "common-048", name: "血刃", tone: "凶", volume: "common", fullNote: "血光损伤?主伤病、手术、流血或激烈冲突。", shortNote: "主伤病、手术、流血或激烈冲突。" },
  { key: "common-049", name: "天财", tone: "吉", volume: "common", fullNote: "偏财机会?主横财、资源、机会财与意外收获。", shortNote: "主横财、资源、机会财与意外收获。" },
  { key: "common-050", name: "天官", tone: "吉", volume: "common", fullNote: "仕名荣誉?主名誉、升迁、体制认可与管理机会。", shortNote: "主名誉、升迁、体制认可与管理机会。" },
  { key: "common-051", name: "天福", tone: "吉", volume: "common", fullNote: "福分顺承?主安稳福气、得人好感与生活顺意。", shortNote: "主安稳福气、得人好感与生活顺意。" },
  { key: "common-052", name: "六秀日", tone: "吉", volume: "common", fullNote: "秀气才情?主外形气质、文艺感、细腻表达。", shortNote: "主外形气质、文艺感、细腻表达。" },
  { key: "common-053", name: "八专", tone: "中", volume: "common", fullNote: "专注偏执?主专一专注，也主执拗与关系偏锋。", shortNote: "主专一专注，也主执拗与关系偏锋。" },
  { key: "common-054", name: "九丑", tone: "凶", volume: "common", fullNote: "情欲困扰?主感情名誉受损、是非与欲望牵连。", shortNote: "主感情名誉受损、是非与欲望牵连。" },
  { key: "uncommon-001", name: "岁德", tone: "吉", volume: "uncommon", fullNote: "岁运护持?主太岁年中有缓冲、助力与人事转圜。", shortNote: "主太岁年中有缓冲、助力与人事转圜。" },
  { key: "uncommon-002", name: "岁德合", tone: "吉", volume: "uncommon", fullNote: "岁运和合?主流年更利修补关系、缓和冲突。", shortNote: "主流年更利修补关系、缓和冲突。" },
  { key: "uncommon-003", name: "岁合", tone: "中", volume: "uncommon", fullNote: "岁气相合?主阶段性合作、顺承与借势。", shortNote: "主阶段性合作、顺承与借势。" },
  { key: "uncommon-004", name: "岁破", tone: "凶", volume: "uncommon", fullNote: "岁运相冲?主流年冲破、变动、折腾与不稳。", shortNote: "主流年冲破、变动、折腾与不稳。" },
  { key: "uncommon-005", name: "岁煞", tone: "凶", volume: "uncommon", fullNote: "岁运煞气?主当年受冲击、麻烦增多、易失衡。", shortNote: "主当年受冲击、麻烦增多、易失衡。" },
  { key: "uncommon-006", name: "岁建", tone: "中", volume: "uncommon", fullNote: "太岁当权?主年份力量重，宜顺势不宜硬顶。", shortNote: "主年份力量重，宜顺势不宜硬顶。" },
  { key: "uncommon-007", name: "官符", tone: "凶", volume: "uncommon", fullNote: "文书规则?主官非、规章、手续、合同压力。", shortNote: "主官非、规章、手续、合同压力。" },
  { key: "uncommon-008", name: "小耗", tone: "凶", volume: "uncommon", fullNote: "小额损耗?主零碎破财、时间精力碎耗。", shortNote: "主零碎破财、时间精力碎耗。" },
  { key: "uncommon-009", name: "大耗", tone: "凶", volume: "uncommon", fullNote: "大额消耗?主较大破耗、资金流失、投入过重。", shortNote: "主较大破耗、资金流失、投入过重。" },
  { key: "uncommon-010", name: "白虎", tone: "凶", volume: "uncommon", fullNote: "刚猛血光?主伤灾、口舌、强硬碰撞与急症。", shortNote: "主伤灾、口舌、强硬碰撞与急症。" },
  { key: "uncommon-011", name: "朱雀", tone: "凶", volume: "uncommon", fullNote: "口舌是非?主言语是非、争执、传播误会。", shortNote: "主言语是非、争执、传播误会。" },
  { key: "uncommon-012", name: "玄武", tone: "凶", volume: "uncommon", fullNote: "隐耗暗事?主隐情、反复、拖延、暗中损耗。", shortNote: "主隐情、反复、拖延、暗中损耗。" },
  { key: "uncommon-013", name: "青龙", tone: "吉", volume: "uncommon", fullNote: "喜事助缘?主喜庆、贵助、顺利开端。", shortNote: "主喜庆、贵助、顺利开端。" },
  { key: "uncommon-014", name: "天后", tone: "中", volume: "uncommon", fullNote: "人情照应?主照料、关系润滑、后援资源。", shortNote: "主照料、关系润滑、后援资源。" },
  { key: "uncommon-015", name: "五鬼", tone: "凶", volume: "uncommon", fullNote: "反复惊扰?主疑心、惊扰、暗耗、无端困扰。", shortNote: "主疑心、惊扰、暗耗、无端困扰。" },
  { key: "uncommon-016", name: "破碎", tone: "凶", volume: "uncommon", fullNote: "结构破损?主计划破散、感情裂痕、器物损坏。", shortNote: "主计划破散、感情裂痕、器物损坏。" },
  { key: "uncommon-017", name: "反吟", tone: "凶", volume: "uncommon", fullNote: "往复相冲?主反复、折返、推倒重来、心神不宁。", shortNote: "主反复、折返、推倒重来、心神不宁。" },
  { key: "uncommon-018", name: "伏吟", tone: "中", volume: "uncommon", fullNote: "原地重复?主停滞、重复、保守，也可稳守。", shortNote: "主停滞、重复、保守，也可稳守。" },
  { key: "uncommon-019", name: "四废", tone: "凶", volume: "uncommon", fullNote: "元气不振?主效率低、动力弱、事倍功半。", shortNote: "主效率低、动力弱、事倍功半。" },
  { key: "uncommon-020", name: "十恶大败", tone: "凶", volume: "uncommon", fullNote: "大败破局?主财务、事业、名声层面的重挫风险。", shortNote: "主财务、事业、名声层面的重挫风险。" },
  { key: "uncommon-021", name: "天转地煞", tone: "凶", volume: "uncommon", fullNote: "天地失序?主气机不稳、外部环境剧烈变动。", shortNote: "主气机不稳、外部环境剧烈变动。" },
  { key: "uncommon-022", name: "天恩", tone: "吉", volume: "uncommon", fullNote: "恩泽庇护?主得宽待、被照拂、逢过可缓。", shortNote: "主得宽待、被照拂、逢过可缓。" },
  { key: "uncommon-023", name: "天愿", tone: "吉", volume: "uncommon", fullNote: "心愿遂意?主所求较易得回应，利许愿与推进。", shortNote: "主所求较易得回应，利许愿与推进。" },
  { key: "uncommon-024", name: "金匮", tone: "吉", volume: "uncommon", fullNote: "财库守成?主收纳、守财、资源沉淀与贵重之物。", shortNote: "主收纳、守财、资源沉淀与贵重之物。" },
  { key: "uncommon-025", name: "玉堂", tone: "吉", volume: "uncommon", fullNote: "名望雅誉?主文雅、名声、礼仪与清贵气。", shortNote: "主文雅、名声、礼仪与清贵气。" },
  { key: "uncommon-026", name: "司命", tone: "吉", volume: "uncommon", fullNote: "掌事安定?主秩序、管理、稳定与责任承接。", shortNote: "主秩序、管理、稳定与责任承接。" },
  { key: "uncommon-027", name: "明堂", tone: "吉", volume: "uncommon", fullNote: "光明显达?主格局舒展、公开展示与气场端正。", shortNote: "主格局舒展、公开展示与气场端正。" },
  { key: "uncommon-028", name: "天牢", tone: "凶", volume: "uncommon", fullNote: "拘束压制?主受限、受困、制度缠身与迟滞。", shortNote: "主受限、受困、制度缠身与迟滞。" },
  { key: "uncommon-029", name: "勾陈", tone: "中", volume: "uncommon", fullNote: "迟滞缠绕?主拖沓、牵扯、保守和现实羁绊。", shortNote: "主拖沓、牵扯、保守和现实羁绊。" },
  { key: "uncommon-030", name: "月煞", tone: "凶", volume: "uncommon", fullNote: "月令耗压?主某月内波折较多、计划受阻。", shortNote: "主某月内波折较多、计划受阻。" },
  { key: "uncommon-031", name: "月害", tone: "凶", volume: "uncommon", fullNote: "月内暗损?主小人、误伤、关系暗耗。", shortNote: "主小人、误伤、关系暗耗。" },
  { key: "uncommon-032", name: "月刑", tone: "凶", volume: "uncommon", fullNote: "月内冲刑?主争执、摩擦、压迫与心烦。", shortNote: "主争执、摩擦、压迫与心烦。" },
  { key: "uncommon-033", name: "月厌", tone: "中", volume: "uncommon", fullNote: "倦怠低迷?主烦躁、厌倦、积极性不足。", shortNote: "主烦躁、厌倦、积极性不足。" },
  { key: "uncommon-034", name: "月虚", tone: "中", volume: "uncommon", fullNote: "虚浮不实?主空忙、计划偏虚、效果打折。", shortNote: "主空忙、计划偏虚、效果打折。" },
  { key: "uncommon-035", name: "月空", tone: "中", volume: "uncommon", fullNote: "落空延后?主期待落空、节奏延误、虚耗。", shortNote: "主期待落空、节奏延误、虚耗。" },
  { key: "uncommon-036", name: "月破", tone: "凶", volume: "uncommon", fullNote: "当月破局?主进程被破、关系折损、安排打散。", shortNote: "主进程被破、关系折损、安排打散。" },
  { key: "uncommon-037", name: "月亡", tone: "凶", volume: "uncommon", fullNote: "月内失守?主精神散乱、判断失稳、暗中漏失。", shortNote: "主精神散乱、判断失稳、暗中漏失。" },
  { key: "uncommon-038", name: "月孤", tone: "中", volume: "uncommon", fullNote: "当月孤清?主当月人际疏离、心态更封闭。", shortNote: "主当月人际疏离、心态更封闭。" },
  { key: "uncommon-039", name: "月厄", tone: "凶", volume: "uncommon", fullNote: "当月厄阻?主麻烦叠加、进退不顺与压力上升。", shortNote: "主麻烦叠加、进退不顺与压力上升。" },
  { key: "uncommon-040", name: "天嗣", tone: "吉", volume: "uncommon", fullNote: "后代缘分?主子嗣、传承、后续发展与延续。", shortNote: "主子嗣、传承、后续发展与延续。" },
  { key: "uncommon-041", name: "天印贵人", tone: "吉", volume: "uncommon", fullNote: "印信资助?主证书、信任、长辈提携与规范背书。", shortNote: "主证书、信任、长辈提携与规范背书。" },
  { key: "uncommon-042", name: "天贵", tone: "吉", volume: "uncommon", fullNote: "贵气临身?主得体、受重视、易逢有分量之人。", shortNote: "主得体、受重视、易逢有分量之人。" },
  { key: "uncommon-043", name: "飞符", tone: "凶", volume: "uncommon", fullNote: "消息惊扰?主突发消息、外部变数、文书扰动。", shortNote: "主突发消息、外部变数、文书扰动。" },
  { key: "uncommon-044", name: "指背煞", tone: "凶", volume: "uncommon", fullNote: "背后议论?主背后非议、小人、受误会。", shortNote: "主背后非议、小人、受误会。" },
  { key: "uncommon-045", name: "六厄", tone: "凶", volume: "uncommon", fullNote: "困顿受压?主阻碍、拖累、劳碌与喘不过气。", shortNote: "主阻碍、拖累、劳碌与喘不过气。" },
  { key: "uncommon-046", name: "六害", tone: "凶", volume: "uncommon", fullNote: "暗害不和?主关系暗害、误会、彼此伤耗。", shortNote: "主关系暗害、误会、彼此伤耗。" },
  { key: "uncommon-047", name: "四离", tone: "凶", volume: "uncommon", fullNote: "离散分隔?主分离、难聚、心神不定与过渡期。", shortNote: "主分离、难聚、心神不定与过渡期。" },
  { key: "uncommon-048", name: "四绝", tone: "凶", volume: "uncommon", fullNote: "气势断绝?主阶段性闭塞、收缩、推进受限。", shortNote: "主阶段性闭塞、收缩、推进受限。" },
  { key: "uncommon-049", name: "归禄", tone: "吉", volume: "uncommon", fullNote: "归元得禄?主回归本位而得利，利稳定收益。", shortNote: "主回归本位而得利，利稳定收益。" },
  { key: "uncommon-050", name: "拱禄", tone: "吉", volume: "uncommon", fullNote: "夹拱成禄?主资源拱护、环境扶持、财禄渐成。", shortNote: "主资源拱护、环境扶持、财禄渐成。" },
  { key: "uncommon-051", name: "夹禄", tone: "吉", volume: "uncommon", fullNote: "两侧扶禄?主外部条件成形，对财禄事业有托举。", shortNote: "主外部条件成形，对财禄事业有托举。" },
  { key: "uncommon-052", name: "病符", tone: "凶", volume: "uncommon", fullNote: "健康耗神?主病气、疲惫、恢复慢、需调养。", shortNote: "主病气、疲惫、恢复慢、需调养。" },
  { key: "uncommon-053", name: "隔角煞", tone: "凶", volume: "uncommon", fullNote: "格格不入?主沟通隔膜、关系偏冷、合拍度不足。", shortNote: "主沟通隔膜、关系偏冷、合拍度不足。" },
  { key: "uncommon-054", name: "井栏叉", tone: "凶", volume: "uncommon", fullNote: "风险受伤?主跌撞、危险动作、水边高处之险。", shortNote: "主跌撞、危险动作、水边高处之险。" },
];

export const SHENSHA_CATALOG_BY_NAME = new Map(SHENSHA_CATALOG.map((item) => [item.name, item]));
